apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  labels:
      app: nginx
      tier: front-end
spec:
  template:
    metadata:
      name: myapp-deployment
      labels:
         app: nginx
         tier: front-end
    spec:
      containers:
      - name: nginx-container
        image: nginx:1.7.1
  replicas: 6
  selector:
    matchLabels:
        tier: front-end
